spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/PI2_GRUPO6
    username: PI2_GRUPO6
    password: AeNoong5
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true


server:
  port: 8084
  servlet:
    context-path: /transactions/

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

