
server:
  port: 8085

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: usuarios-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: false
        service-id: config-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: moviesdb
      port: 27017
      host: mongodb

  main:
    allow-circular-references: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8082/realms/DigitalMedia
          jwk-set-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8082/realms/DigitalMedia/openid-connect/token
        registration:
          keycloak:
            client-id: microservicios
            client-secret: bsFPyChwi3sfCl5Mm00SGckDCKnq3KnQ
            authorization-grant-type: authorization_code

dh:
  keycloak:
    serverUrl: http://localhost:8082/
    realm: DigitalMedia
    clientId: internal

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

