spring:
  application:
    name: eureka-service

  #cloud:
  #  config:
  #    discovery:
  #      enable: true
  #      id-service: config-service

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-service
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

