server:
  port: ${PORT:8084}

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: facturacion-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: false
        service-id: config-service
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          facturacion:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
            token-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/token
        registration:
          facturacion:
            provider: facturacion
            client-id: microservicios
            client-secret: mB1uCqMvGb1YFIsnIhNTXb9GOa8TYHfI
            authorization-grant-type: client_credentials
            scope: openid
            redirect-uri: http://localhost:8080/*

  datasource:
    url: jdbc:h2:mem:moviesdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  enabled: true

