version: "3.9"  # optional since v1.27.0

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5439:5439'
    networks:
      - local-keycloak
    volumes:
      - db:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - local-keycloak
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - '8081:8081'
    networks:
      - local-keycloak
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
  eureka-service:
    build: ./eureka-server
    image: eureka-service:1
    container_name: eureka-service
    networks:
      - local-keycloak
    mem_limit: 512m
    ports:
      - '8761:8761'
  config-service:
    image: config-service:1
    container_name: config-service
    build:
      context: ./config-service
      dockerfile: ./Dockerfile
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka
    networks:
      - local-keycloak
    ports:
      - '8888:8888'
    restart: always
  api-gateway:
    build: ./api-gateway
    depends_on:
      - eureka-service
      - keycloak
    image: api-gateway:1
    container_name: api-gateway
    mem_limit: 512m
    ports:
      - '8090:8090'
    networks:
      - local-keycloak
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka
      KEYCLOAK_URL: http://localhost:8082/
    restart: always
  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_PASSWORD: 1234
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realms/DigitalMedia-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - '8082:8080'
    restart: unless-stopped
    networks:
      - local-keycloak
  facturacion:
    build: ./facturacion
    depends_on:
      - eureka-service
    image: facturacion:1
    container_name: facturacion-service
    mem_limit: 512m
    ports:
      - '8084:8084'
    networks:
      - local-keycloak
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka
      KEYCLOAK_URL: http://localhost:8082/
  usuarios-service:
    build: ./usuarios-service
    depends_on:
      - mongodb
      - eureka-service
    image: usuarios-service:1
    container_name: usuarios-service
    mem_limit: 512m
    ports:
      - '8085:8085'
    networks:
      - local-keycloak
    environment:
      DB_URL: mongodb://mongodb:27017/moviesdb
      EUREKA_URL: http://eureka-service:8761/eureka
      KEYCLOAK_URL: http://keycloak:8082/
  peliculas-service:
    build: ./peliculas-api
    depends_on:
      - mongodb
      - eureka-service
    image: peliculas-service:1
    container_name: peliculas-service
    mem_limit: 512m
    ports:
      - '8086:8086'
    networks:
      - local-keycloak
    environment:
      DB_URL: mongodb://mongodb:27017/moviesdb
      EUREKA_URL: http://eureka-service:8761/eureka
      KEYCLOAK_URL: http://localhost:8082/

networks:
  local-keycloak:

volumes:
  db:
