package com.dh.accountservice.domain.enums;

public enum EMessageCode {
    
    API_RATE_LIMIT,
    ERROR_SENDING_EMAIL,

    INVALID_TOKEN,

    RESOURCE_NOT_FOUND_BY_ID,
    RESOURCE_NOT_FIND_BY_ID,
    USER_NOT_FOUND_BY_EMAIL,
    USER_NOT_FOUND_BY_ID,
    USER_NOT_FOUND_BY_USERNAME,
    USER_EXIST_BY_EMAIL_USERNAME,
    ALIAS_EXIST,
    NOT_EXIST_ACCOUNT,
    CONEXION_ERROR,
    LOGIN_ERROR,
    USER_UNAUTHORIZED,
    ACOUNT_NOT_FOUND_BY_ID,
    ACOUNT_NOT_FOUND_BY_USER_ID,
    ACCOUNT_NOT_EXIST_BY_USER_ID,
    ALIAS_FORMAT_INCORRECT,
    INSUFFICIENT_FUNDS,
    NOT_ACCES,
    ACOUNT_NOT_FOUND_BY_CVU
    
}
