server:
  port: 8050

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: accountRoute
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: userRoute
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: transactionRoute
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
