server:
  port: 8083

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: peliculas-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: false
        service-id: config-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: moviesdb
      port: 27017
      host: mongodb
      uri: ${DB_URL}

  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        provider:
          digital-house:
            issuer-uri: http://keycloak:8082/realms/DigitalMedia
        registration:
          digital-house:
            provider: digital-house
            client-id: microservicios
            client-secret: mB1uCqMvGb1YFIsnIhNTXb9GOa8TYHfI
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:8080/*
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
